
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUM idcalculadora : comandos\n    comandos : comando comandos\n             |\n    comando : '$' idcomando : '?' idcomando : '!' expressaocomando : id '=' expressaocomando : '!' '!'expressao : expressao '+' termoexpressao : expressao '-' termoexpressao : termotermo : termo '*' fatortermo : termo '/' fatortermo : fatorfator : idfator : NUMfator : '(' expressao ')'"
    
_lr_action_items = {'$end':([0,1,2,3,8,9,11,12,13,14,15,16,17,19,25,26,27,28,29,],[-3,0,-1,-3,-2,-4,-5,-8,-6,-11,-14,-15,-16,-7,-9,-10,-12,-13,-17,]),'$':([0,3,9,11,12,13,14,15,16,17,19,25,26,27,28,29,],[4,4,-4,-5,-8,-6,-11,-14,-15,-16,-7,-9,-10,-12,-13,-17,]),'?':([0,3,9,11,12,13,14,15,16,17,19,25,26,27,28,29,],[6,6,-4,-5,-8,-6,-11,-14,-15,-16,-7,-9,-10,-12,-13,-17,]),'!':([0,3,7,9,11,12,13,14,15,16,17,19,25,26,27,28,29,],[7,7,12,-4,-5,-8,-6,-11,-14,-15,-16,-7,-9,-10,-12,-13,-17,]),'id':([0,3,4,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,],[5,5,9,11,16,-4,16,-5,-8,-6,-11,-14,-15,-16,16,-7,16,16,16,16,-9,-10,-12,-13,-17,]),'=':([5,],[10,]),'NUM':([7,10,18,20,21,22,23,],[17,17,17,17,17,17,17,]),'(':([7,10,18,20,21,22,23,],[18,18,18,18,18,18,18,]),'+':([13,14,15,16,17,19,24,25,26,27,28,29,],[20,-11,-14,-15,-16,20,20,-9,-10,-12,-13,-17,]),'-':([13,14,15,16,17,19,24,25,26,27,28,29,],[21,-11,-14,-15,-16,21,21,-9,-10,-12,-13,-17,]),')':([14,15,16,17,24,25,26,27,28,29,],[-11,-14,-15,-16,29,-9,-10,-12,-13,-17,]),'*':([14,15,16,17,25,26,27,28,29,],[22,-14,-15,-16,22,22,-12,-13,-17,]),'/':([14,15,16,17,25,26,27,28,29,],[23,-14,-15,-16,23,23,-12,-13,-17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calculadora':([0,],[1,]),'comandos':([0,3,],[2,8,]),'comando':([0,3,],[3,3,]),'expressao':([7,10,18,],[13,19,24,]),'termo':([7,10,18,20,21,],[14,14,14,25,26,]),'fator':([7,10,18,20,21,22,23,],[15,15,15,15,15,27,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calculadora","S'",1,None,None,None),
  ('calculadora -> comandos','calculadora',1,'p_calculadora','calculadora_yacc.py',6),
  ('comandos -> comando comandos','comandos',2,'p_comandos','calculadora_yacc.py',10),
  ('comandos -> <empty>','comandos',0,'p_comandos','calculadora_yacc.py',11),
  ('comando -> $ id','comando',2,'p_comando_declaracao','calculadora_yacc.py',15),
  ('comando -> ? id','comando',2,'p_comando_leitura','calculadora_yacc.py',19),
  ('comando -> ! expressao','comando',2,'p_comando_escrita','calculadora_yacc.py',24),
  ('comando -> id = expressao','comando',3,'p_comando_atribuicao','calculadora_yacc.py',28),
  ('comando -> ! !','comando',2,'p_comando_informacao','calculadora_yacc.py',32),
  ('expressao -> expressao + termo','expressao',3,'p_expressao_mais','calculadora_yacc.py',36),
  ('expressao -> expressao - termo','expressao',3,'p_expressao_menos','calculadora_yacc.py',40),
  ('expressao -> termo','expressao',1,'p_expressao_termo','calculadora_yacc.py',44),
  ('termo -> termo * fator','termo',3,'p_termo_multi','calculadora_yacc.py',48),
  ('termo -> termo / fator','termo',3,'p_termo_div','calculadora_yacc.py',52),
  ('termo -> fator','termo',1,'p_termo_fator','calculadora_yacc.py',56),
  ('fator -> id','fator',1,'p_fator_id','calculadora_yacc.py',60),
  ('fator -> NUM','fator',1,'p_fator_num','calculadora_yacc.py',67),
  ('fator -> ( expressao )','fator',3,'p_fator_expressao','calculadora_yacc.py',71),
]
